// Minimal gRPC contract for sing-box's V2Ray stats service, sufficient to poll
// per-user traffic counters. The gRPC service is registered by sing-box under
// the V2Ray-compatible name "v2ray.core.app.stats.command.StatsService" (its
// .proto file's package differs, but the runtime service name is this one), so
// this package name and the field numbers must match for wire compatibility.
// This definition and the generated Go code are our own.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: internal/v2rayapi/stats.proto

package v2rayapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Stat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         int64                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_internal_v2rayapi_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v2rayapi_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_internal_v2rayapi_stats_proto_rawDescGZIP(), []int{0}
}

func (x *Stat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stat) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type QueryStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Reset_        bool                   `protobuf:"varint,2,opt,name=reset,proto3" json:"reset,omitempty"`
	Patterns      []string               `protobuf:"bytes,3,rep,name=patterns,proto3" json:"patterns,omitempty"`
	Regexp        bool                   `protobuf:"varint,4,opt,name=regexp,proto3" json:"regexp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatsRequest) Reset() {
	*x = QueryStatsRequest{}
	mi := &file_internal_v2rayapi_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatsRequest) ProtoMessage() {}

func (x *QueryStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v2rayapi_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryStatsRequest) Descriptor() ([]byte, []int) {
	return file_internal_v2rayapi_stats_proto_rawDescGZIP(), []int{1}
}

func (x *QueryStatsRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *QueryStatsRequest) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

func (x *QueryStatsRequest) GetPatterns() []string {
	if x != nil {
		return x.Patterns
	}
	return nil
}

func (x *QueryStatsRequest) GetRegexp() bool {
	if x != nil {
		return x.Regexp
	}
	return false
}

type QueryStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stat          []*Stat                `protobuf:"bytes,1,rep,name=stat,proto3" json:"stat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatsResponse) Reset() {
	*x = QueryStatsResponse{}
	mi := &file_internal_v2rayapi_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatsResponse) ProtoMessage() {}

func (x *QueryStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_v2rayapi_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatsResponse.ProtoReflect.Descriptor instead.
func (*QueryStatsResponse) Descriptor() ([]byte, []int) {
	return file_internal_v2rayapi_stats_proto_rawDescGZIP(), []int{2}
}

func (x *QueryStatsResponse) GetStat() []*Stat {
	if x != nil {
		return x.Stat
	}
	return nil
}

var File_internal_v2rayapi_stats_proto protoreflect.FileDescriptor

const file_internal_v2rayapi_stats_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/v2rayapi/stats.proto\x12\x1cv2ray.core.app.stats.command\"0\n" +
	"\x04Stat\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\"w\n" +
	"\x11QueryStatsRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x14\n" +
	"\x05reset\x18\x02 \x01(\bR\x05reset\x12\x1a\n" +
	"\bpatterns\x18\x03 \x03(\tR\bpatterns\x12\x16\n" +
	"\x06regexp\x18\x04 \x01(\bR\x06regexp\"L\n" +
	"\x12QueryStatsResponse\x126\n" +
	"\x04stat\x18\x01 \x03(\v2\".v2ray.core.app.stats.command.StatR\x04stat2\x81\x01\n" +
	"\fStatsService\x12q\n" +
	"\n" +
	"QueryStats\x12/.v2ray.core.app.stats.command.QueryStatsRequest\x1a0.v2ray.core.app.stats.command.QueryStatsResponse\"\x00B8Z6github.com/tanselxy/singbox/internal/v2rayapi;v2rayapib\x06proto3"

var (
	file_internal_v2rayapi_stats_proto_rawDescOnce sync.Once
	file_internal_v2rayapi_stats_proto_rawDescData []byte
)

func file_internal_v2rayapi_stats_proto_rawDescGZIP() []byte {
	file_internal_v2rayapi_stats_proto_rawDescOnce.Do(func() {
		file_internal_v2rayapi_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_v2rayapi_stats_proto_rawDesc), len(file_internal_v2rayapi_stats_proto_rawDesc)))
	})
	return file_internal_v2rayapi_stats_proto_rawDescData
}

var file_internal_v2rayapi_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_v2rayapi_stats_proto_goTypes = []any{
	(*Stat)(nil),               // 0: v2ray.core.app.stats.command.Stat
	(*QueryStatsRequest)(nil),  // 1: v2ray.core.app.stats.command.QueryStatsRequest
	(*QueryStatsResponse)(nil), // 2: v2ray.core.app.stats.command.QueryStatsResponse
}
var file_internal_v2rayapi_stats_proto_depIdxs = []int32{
	0, // 0: v2ray.core.app.stats.command.QueryStatsResponse.stat:type_name -> v2ray.core.app.stats.command.Stat
	1, // 1: v2ray.core.app.stats.command.StatsService.QueryStats:input_type -> v2ray.core.app.stats.command.QueryStatsRequest
	2, // 2: v2ray.core.app.stats.command.StatsService.QueryStats:output_type -> v2ray.core.app.stats.command.QueryStatsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_v2rayapi_stats_proto_init() }
func file_internal_v2rayapi_stats_proto_init() {
	if File_internal_v2rayapi_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_v2rayapi_stats_proto_rawDesc), len(file_internal_v2rayapi_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_v2rayapi_stats_proto_goTypes,
		DependencyIndexes: file_internal_v2rayapi_stats_proto_depIdxs,
		MessageInfos:      file_internal_v2rayapi_stats_proto_msgTypes,
	}.Build()
	File_internal_v2rayapi_stats_proto = out.File
	file_internal_v2rayapi_stats_proto_goTypes = nil
	file_internal_v2rayapi_stats_proto_depIdxs = nil
}
